version: '3.7'
services:
  tasksdb:
    image: postgres:latest
    user: postgres
    restart: always
    networks:
      - backend
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - tasks_data:/var/lib/postgresql/tasks_data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - ./config/.env
    depends_on:
      tasksdb:
        condition: service_healthy
    networks:
      - backend
volumes:
  tasks_data:

networks:
  backend:
    driver: bridge